name = "gamezone-ai-video"
main = "index.js"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGINS = "https://gajpalmi.github.io"
HF_SPACE_BASE = "https://cbensimon-wan2-2-fp8da-aoti-preview2.hf.space"
HF_FN_NAME = "generate_video"

[observability]
enabled = true
